runtime: nodejs18


env_variables: 
  GALLERY_DB_URI: "mongodb+srv://xwang1994:5dj8VVXwxt8gIqKp@cluster0.2ofz93u.mongodb.net/gallery_infinity_db?retryWrites=true&w=majority "
  GALLERY_COLLECTION: "gallery_infinity_db"